version: '3'
services:
  mailsender:
    image: patrickgeorge1/share-with-ukraine-mailsender:kafka-mail-sender-ci-cd-00033-a44e76c-20220510002237
    environment:
      MAIL_USERNAME: 'ShareWithUkraine.mailsender@gmail.com'
      MAIL_PASSWORD: 'hqulycowxysovuzi'
      MAIL_SUBJECT: 'Share with Ukraine - Status Notification'
      KAFKA_CONSUMER_GROUP: email-sender
      KAFKA_BOOTSTRAP_SERVERS: broker:9092
      KAFKA_TOPIC_NAME: email-tasks
networks:
  default:
    external:
      name: cluster_shared_network