apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/blessed/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sun, 17 Apr 2022 22:54:57 EEST
        provider: minikube.sigs.k8s.io
        version: v1.25.2
      name: cluster_info
    server: https://127.0.0.1:50059
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sun, 17 Apr 2022 22:54:57 EEST
        provider: minikube.sigs.k8s.io
        version: v1.25.2
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/blessed/.minikube/profiles/minikube/client.crt
    client-key: /Users/blessed/.minikube/profiles/minikube/client.key
