version : '3'

services :
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf


networks:
  default:
    external:
      name: cluster_shared_network