version: '3'
services:

  prometheus:
      image: prom/prometheus
      container_name: prometheus
      volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
          - 9090:9090