
name: CI/CD

on:
  push:
    branches: [ ci-cd ]
  pull_request:
    branches: [ ci-cd ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: "Build (+ dependency check)"
      run: npm install
    - name: "Test"
      run: npm test --passWithNoTests

  publish-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
    - uses: actions/checkout@v3
    - name: "Docker login"
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    
    - name: "Docker push"
      run: make publish-frontend